LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := clib
LOCAL_C_INCLUDES := $(LOCAL_PATH)/../ $(LOCAL_PATH)
LOCAL_CFLAGS := -DRIG_ENABLE_DEBUG -DSFMT_MEXP=19937 -DHAVE_CONFIG_H
LOCAL_SRC_FILES := $(wildcard $(LOCAL_PATH)/*.c)
LOCAL_EXPORT_CFLAGS := -I$(LOCAL_PATH)

include $(BUILD_STATIC_LIBRARY)
